import "./css/iconfont/iconfont.ttf"
import "./css/iconfont/iconfont.woff2"
import "./css/iconfont/iconfont.woff"
import "./css/account.css"
import "./css/base.css"
import "./css/common.css"
import "./css/iconfont.css"
import "./css/index.css"
import "./sign_up.css"

import "./js/account.js"
import "./js/index.js"
import "./js/sign_up.js"
import "./js/jquery-1.11.1min.js"
